# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20161210_1249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='my_blog',
            new_name='blogs',
        ),
    ]
