# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20161219_1347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogs',
            new_name='myblog_blogs',
        ),
    ]
